//! YAML concrete syntax trees of rendered skeletons, parsed by the
//! tree-sitter YAML grammar.
//!
//! The grammar resolves plain scalars with the YAML 1.2 core schema, while
//! Helm reads YAML 1.1: `y`, `yes` and `on` are booleans and `010` is octal
//! there. The tree therefore supplies structure and scalar style only; a
//! plain scalar's type or value never comes from the grammar's scalar kinds.
//!
//! [`arm_layout`] builds one arm's skeleton (its rendered text, with a
//! placeholder for each hole whose shape is proved) and maps the skeleton's
//! YAML nodes back to the pieces that produced them. Error-free parsing is
//! necessary but not sufficient: every permitted substitution of a
//! placeholder must leave the structure in place, or the arm is uncertain.

use crate::Span;
use crate::rendered::{HoleShape, LayoutUncertainty, RenderedArm, RenderedBody, RenderedPiece};

thread_local! {
    /// A `Parser` is far more expensive to build than to reuse.
    static YAML_PARSER: std::cell::RefCell<Option<tree_sitter::Parser>> =
        std::cell::RefCell::new(new_yaml_parser());
}

fn new_yaml_parser() -> Option<tree_sitter::Parser> {
    let language = tree_sitter::Language::new(tree_sitter_yaml::LANGUAGE);
    let mut parser = tree_sitter::Parser::new();
    parser.set_language(&language).ok()?;
    Some(parser)
}

/// Parse `text` as a YAML stream. `None` when the grammar cannot be loaded
/// or the parse is cancelled; a malformed stream still yields a tree whose
/// error and missing nodes mark the malformed parts.
#[must_use]
pub fn parse_yaml(text: &str) -> Option<tree_sitter::Tree> {
    YAML_PARSER.with_borrow_mut(|parser| parser.as_mut()?.parse(text, None))
}

/// The text one arm renders, with provenance for every generated byte.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Skeleton {
    /// The rendered text, with a placeholder token for each hole.
    pub text: String,
    /// Which piece produced each byte range of `text`, in order.
    pub segments: Vec<SkeletonSegment>,
}

/// One piece's bytes in a [`Skeleton`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SkeletonSegment {
    /// The byte range in [`Skeleton::text`].
    pub range: Span,
    /// The arm-local index of the piece in [`RenderedArm::pieces`].
    pub piece: usize,
    /// The bytes are a synthetic placeholder for a hole, never output text.
    pub placeholder: bool,
}

/// The layout of one arm.
#[derive(Clone, Debug, PartialEq)]
pub enum ArmLayout {
    /// The skeleton's YAML structure holds for every permitted hole output.
    Known(YamlOwnership),
    /// Nothing is claimed about the arm's YAML placement.
    Uncertain(LayoutUncertainty),
}

/// The YAML nodes of an arm's skeleton and the pieces each one owns.
#[derive(Clone, Debug, PartialEq)]
pub struct YamlOwnership {
    /// Structural nodes in document order; parents precede children.
    pub nodes: Vec<YamlNode>,
    /// The block scalars among `nodes`, with their decoded headers.
    pub blocks: Vec<BlockScalarOwnership>,
    /// The documents' values from the literal decoder, when the arm renders
    /// literal text only (never from placeholder text).
    pub decoded: Option<Vec<serde_yaml::Value>>,
}

/// One structural YAML node.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct YamlNode {
    /// The enclosing structural node.
    pub parent: Option<usize>,
    /// What the node is.
    pub kind: YamlNodeKind,
    /// The node's bytes in the skeleton.
    pub span: Span,
    /// The arm-local piece indices `[first, last]` whose bytes the node
    /// covers; `None` for a node of no bytes.
    pub pieces: Option<(usize, usize)>,
}

/// The structural node kinds ownership is expressed in.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum YamlNodeKind {
    /// A YAML document.
    Document,
    /// A block mapping.
    Mapping,
    /// A block mapping entry.
    Pair,
    /// A block sequence.
    Sequence,
    /// A block sequence item.
    Item,
    /// A flow mapping `{…}`.
    FlowMapping,
    /// A flow mapping entry.
    FlowPair,
    /// A flow sequence `[…]`.
    FlowSequence,
    /// A flow scalar of the given style.
    Scalar(ScalarStyle),
    /// A `|` or `>` block scalar.
    BlockScalar,
    /// A `#` comment.
    Comment,
}

/// The style of a flow scalar.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ScalarStyle {
    /// Unquoted.
    Plain,
    /// `'…'`.
    SingleQuoted,
    /// `"…"`.
    DoubleQuoted,
}

/// A block scalar and its header.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BlockScalarOwnership {
    /// The block scalar's index in [`YamlOwnership::nodes`].
    pub node: usize,
    /// The decoded `|`/`>` header.
    pub header: BlockHeader,
}

/// A block scalar header, decoded as YAML defines it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BlockHeader {
    /// `|` keeps line breaks; `>` folds them.
    pub folded: bool,
    /// What happens to the final line breaks.
    pub chomping: Chomping,
    /// The explicit indentation indicator (`|2`), if any.
    pub indentation: Option<u8>,
}

/// Block scalar chomping.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Chomping {
    /// Default: keep one final line break.
    Clip,
    /// `-`: drop the final line breaks.
    Strip,
    /// `+`: keep every final line break.
    Keep,
}

/// The skeleton of `arm` and the layout it proves. A hole becomes a
/// placeholder only when its shape proves it stays inside one scalar token;
/// any other hole makes the arm uncertain.
#[must_use]
pub fn arm_layout(body: &RenderedBody, arm: &RenderedArm, source: &str) -> (Skeleton, ArmLayout) {
    let skeleton = build_skeleton(body, arm, source, false);
    let mut may_be_empty = false;
    for piece in &arm.pieces {
        match body.pieces.get(piece.0) {
            Some(RenderedPiece::Hole {
                shape: HoleShape::Unknown,
                ..
            }) => return (skeleton, ArmLayout::Uncertain(LayoutUncertainty::RawHole)),
            Some(RenderedPiece::Hole {
                shape: HoleShape::ScalarText { nonempty: false },
                ..
            }) => may_be_empty = true,
            _ => {}
        }
    }
    let layout = match ownership(&skeleton) {
        Err(uncertainty) => ArmLayout::Uncertain(uncertainty),
        // An empty output is a permitted substitution too: it must leave the
        // same structure (a placeholder-only scalar may vanish with it).
        Ok(owned) if may_be_empty => {
            let empty = build_skeleton(body, arm, source, true);
            match ownership(&empty) {
                Ok(empty_owned)
                    if structure(&owned, &skeleton) == structure(&empty_owned, &empty) =>
                {
                    ArmLayout::Known(owned)
                }
                Ok(_) => ArmLayout::Uncertain(LayoutUncertainty::Substitution),
                Err(uncertainty) => ArmLayout::Uncertain(uncertainty),
            }
        }
        Ok(owned) => ArmLayout::Known(owned),
    };
    (skeleton, layout)
}

/// Concatenate the arm's pieces: literals verbatim, holes as a placeholder
/// token (or nothing, for the empty substitution).
fn build_skeleton(body: &RenderedBody, arm: &RenderedArm, source: &str, empty: bool) -> Skeleton {
    let mut text = String::new();
    let mut segments = Vec::new();
    for (index, piece) in arm.pieces.iter().enumerate() {
        let start = text.len();
        let placeholder = match body.pieces.get(piece.0) {
            Some(RenderedPiece::Text { span, .. }) => {
                text.push_str(source.get(span.start..span.end).unwrap_or_default());
                false
            }
            Some(RenderedPiece::Hole { .. }) => {
                if !empty {
                    text.push('h');
                    text.push_str(&index.to_string());
                }
                true
            }
            None => false,
        };
        segments.push(SkeletonSegment {
            range: Span::new(start, text.len()),
            piece: index,
            placeholder,
        });
    }
    Skeleton { text, segments }
}

/// Parse the skeleton and map its structural nodes to pieces.
fn ownership(skeleton: &Skeleton) -> Result<YamlOwnership, LayoutUncertainty> {
    let tree = parse_yaml(&skeleton.text).ok_or(LayoutUncertainty::Parse)?;
    let root = tree.root_node();
    if root.has_error() {
        return Err(LayoutUncertainty::Parse);
    }
    let mut owned = YamlOwnership {
        nodes: Vec::new(),
        blocks: Vec::new(),
        decoded: None,
    };
    collect_nodes(root, None, skeleton, &mut owned)?;
    if skeleton.segments.iter().all(|segment| !segment.placeholder) {
        owned.decoded = decode_documents(&skeleton.text);
    }
    Ok(owned)
}

fn collect_nodes(
    node: tree_sitter::Node<'_>,
    parent: Option<usize>,
    skeleton: &Skeleton,
    owned: &mut YamlOwnership,
) -> Result<(), LayoutUncertainty> {
    let kind = match node.kind() {
        "tag" | "alias" => return Err(LayoutUncertainty::TagOrAlias),
        "document" => Some(YamlNodeKind::Document),
        "block_mapping" => Some(YamlNodeKind::Mapping),
        "block_mapping_pair" => Some(YamlNodeKind::Pair),
        "block_sequence" => Some(YamlNodeKind::Sequence),
        "block_sequence_item" => Some(YamlNodeKind::Item),
        "flow_mapping" => Some(YamlNodeKind::FlowMapping),
        "flow_pair" => Some(YamlNodeKind::FlowPair),
        "flow_sequence" => Some(YamlNodeKind::FlowSequence),
        "plain_scalar" => Some(YamlNodeKind::Scalar(ScalarStyle::Plain)),
        "single_quote_scalar" => Some(YamlNodeKind::Scalar(ScalarStyle::SingleQuoted)),
        "double_quote_scalar" => Some(YamlNodeKind::Scalar(ScalarStyle::DoubleQuoted)),
        "block_scalar" => Some(YamlNodeKind::BlockScalar),
        "comment" => Some(YamlNodeKind::Comment),
        _ => None,
    };
    let mut own_parent = parent;
    if let Some(kind) = kind {
        let span = Span::new(node.start_byte(), node.end_byte());
        let index = owned.nodes.len();
        owned.nodes.push(YamlNode {
            parent,
            kind,
            span,
            pieces: covered_pieces(skeleton, span),
        });
        if kind == YamlNodeKind::BlockScalar {
            let text = skeleton.text.get(span.start..span.end).unwrap_or_default();
            owned.blocks.push(BlockScalarOwnership {
                node: index,
                header: block_header(text).ok_or(LayoutUncertainty::Parse)?,
            });
        }
        // Scalars are leaves of the ownership structure.
        if matches!(kind, YamlNodeKind::Scalar(_) | YamlNodeKind::BlockScalar) {
            return Ok(());
        }
        own_parent = Some(index);
    }
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        collect_nodes(child, own_parent, skeleton, owned)?;
    }
    Ok(())
}

/// The first and last arm-local pieces whose bytes intersect `span`.
fn covered_pieces(skeleton: &Skeleton, span: Span) -> Option<(usize, usize)> {
    let mut covered = skeleton
        .segments
        .iter()
        .filter(|segment| segment.range.start < span.end && span.start < segment.range.end);
    let first = covered.next()?.piece;
    let last = covered.next_back().map_or(first, |segment| segment.piece);
    Some((first, last))
}

/// Decode a block scalar header: `|` or `>`, then at most one chomping
/// indicator and one indentation digit in either order, as YAML 1.2 §8.1.1
/// defines it. The header ends at the first blank, comment or line break.
fn block_header(text: &str) -> Option<BlockHeader> {
    let mut chars = text.chars();
    let folded = match chars.next()? {
        '|' => false,
        '>' => true,
        _ => return None,
    };
    let mut chomping = None;
    let mut indentation = None;
    for c in chars {
        match c {
            '-' | '+' if chomping.is_none() => {
                chomping = Some(if c == '-' {
                    Chomping::Strip
                } else {
                    Chomping::Keep
                });
            }
            '1'..='9' if indentation.is_none() => indentation = c.to_digit(10)?.try_into().ok(),
            ' ' | '\t' | '\r' | '\n' | '#' => break,
            _ => return None,
        }
    }
    Some(BlockHeader {
        folded,
        chomping: chomping.unwrap_or(Chomping::Clip),
        indentation,
    })
}

/// Every document of a literal-only skeleton, from the literal decoder.
fn decode_documents(text: &str) -> Option<Vec<serde_yaml::Value>> {
    use serde::Deserialize as _;
    serde_yaml::Deserializer::from_str(text)
        .map(serde_yaml::Value::deserialize)
        .collect::<Result<Vec<_>, _>>()
        .ok()
}

/// The structure a substitution must preserve: every node's kind and parent
/// kind, except a scalar made only of placeholder bytes (an empty output may
/// remove it without moving anything else).
fn structure(
    owned: &YamlOwnership,
    skeleton: &Skeleton,
) -> Vec<(YamlNodeKind, Option<YamlNodeKind>)> {
    let placeholder_only = |node: &YamlNode| {
        matches!(node.kind, YamlNodeKind::Scalar(_))
            && skeleton.segments.iter().all(|segment| {
                segment.placeholder
                    || segment.range.end <= node.span.start
                    || node.span.end <= segment.range.start
            })
    };
    owned
        .nodes
        .iter()
        .filter(|node| !placeholder_only(node))
        .map(|node| {
            let parent = node
                .parent
                .and_then(|parent| owned.nodes.get(parent))
                .map(|parent| parent.kind);
            (node.kind, parent)
        })
        .collect()
}

#[cfg(test)]
#[path = "tests/yaml.rs"]
mod tests;
