//! YAML concrete syntax trees of rendered skeletons, parsed by the
//! tree-sitter YAML grammar.
//!
//! The grammar resolves plain scalars with the YAML 1.2 core schema, while
//! Helm reads YAML 1.1: `y`, `yes` and `on` are booleans and `010` is octal
//! there. The tree therefore supplies structure and scalar style only; a
//! plain scalar's type or value never comes from the grammar's scalar kinds.
//!
//! [`arm_layout`] builds one arm's skeleton (its rendered text, with a
//! placeholder for each hole whose shape is proved) and maps the skeleton's
//! YAML nodes back to the pieces that produced them. Error-free parsing is
//! necessary but not sufficient: every permitted substitution of a
//! placeholder must leave the structure in place, or the arm is uncertain.

use crate::Span;
use crate::rendered::{HoleShape, LayoutUncertainty, RenderedArm, RenderedBody, RenderedPiece};
use crate::yaml_dialect::{DialectDivergence, plain_scalar_divergence};

/// Upper bound on one arm's skeleton, in bytes. It is well above the largest
/// template of the chart corpus (a 1.4 MB CRD); a larger skeleton is
/// [`LayoutUncertainty::Overflow`] and is never parsed.
pub const MAX_SKELETON_BYTES: usize = 4 << 20;

thread_local! {
    /// A `Parser` is far more expensive to build than to reuse.
    static YAML_PARSER: std::cell::RefCell<Option<tree_sitter::Parser>> =
        std::cell::RefCell::new(new_yaml_parser());
}

fn new_yaml_parser() -> Option<tree_sitter::Parser> {
    let language = tree_sitter::Language::new(tree_sitter_yaml::LANGUAGE);
    let mut parser = tree_sitter::Parser::new();
    parser.set_language(&language).ok()?;
    Some(parser)
}

/// Parse `text` as a YAML stream. `None` when the grammar cannot be loaded
/// or the parse is cancelled; a malformed stream still yields a tree whose
/// error and missing nodes mark the malformed parts.
#[must_use]
pub fn parse_yaml(text: &str) -> Option<tree_sitter::Tree> {
    YAML_PARSER.with_borrow_mut(|parser| parser.as_mut()?.parse(text, None))
}

/// The text one arm renders, with provenance for every generated byte.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Skeleton {
    /// The rendered text, with a placeholder token for each hole.
    pub text: String,
    /// Which piece produced each byte range of `text`, in order.
    pub segments: Vec<SkeletonSegment>,
}

/// One piece's bytes in a [`Skeleton`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SkeletonSegment {
    /// The byte range in [`Skeleton::text`].
    pub range: Span,
    /// The arm-local index of the piece in [`RenderedArm::pieces`].
    pub piece: usize,
    /// The bytes are a synthetic placeholder for a hole, never output text.
    pub placeholder: bool,
}

/// The layout of one arm.
#[derive(Clone, Debug, PartialEq)]
pub enum ArmLayout {
    /// The skeleton's YAML structure holds for every permitted hole output.
    Known(YamlOwnership),
    /// Nothing is claimed about the arm's YAML placement.
    Uncertain(LayoutUncertainty),
}

/// The YAML nodes of an arm's skeleton and the pieces each one owns.
#[derive(Clone, Debug, PartialEq)]
pub struct YamlOwnership {
    /// The skeleton the node spans index.
    pub skeleton: Skeleton,
    /// Structural nodes in document order; parents precede children.
    pub nodes: Vec<YamlNode>,
    /// The block scalars among `nodes`, with their decoded headers.
    pub blocks: Vec<BlockScalarOwnership>,
    /// The documents' values as Helm decodes them, or why they are withheld.
    pub decoded: Result<Vec<serde_json::Value>, Undecoded>,
}

/// Why an arm's decoded values are withheld while its structure is known.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Undecoded {
    /// The arm renders hole output, whose text is not known.
    Placeholders,
    /// A plain scalar Helm's YAML 1.1 reading decodes differently.
    Dialect(DialectDivergence),
    /// A collection as a mapping key.
    CollectionKey,
    /// The literal decoder refuses the text.
    Refused,
}

/// One structural YAML node.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct YamlNode {
    /// The enclosing structural node.
    pub parent: Option<usize>,
    /// What the node is.
    pub kind: YamlNodeKind,
    /// The node is the key of its mapping entry.
    pub key: bool,
    /// The node's bytes in the skeleton.
    pub span: Span,
    /// The arm-local piece indices `[first, last]` whose bytes the node
    /// covers; `None` for a node of no bytes.
    pub pieces: Option<(usize, usize)>,
}

/// The structural node kinds ownership is expressed in.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum YamlNodeKind {
    /// A YAML document.
    Document,
    /// A block mapping.
    Mapping,
    /// A block mapping entry.
    Pair,
    /// A block sequence.
    Sequence,
    /// A block sequence item.
    Item,
    /// A flow mapping `{…}`.
    FlowMapping,
    /// A flow mapping entry.
    FlowPair,
    /// A flow sequence `[…]`.
    FlowSequence,
    /// A flow scalar of the given style.
    Scalar(ScalarStyle),
    /// A `|` or `>` block scalar.
    BlockScalar,
    /// A `#` comment.
    Comment,
}

impl YamlNodeKind {
    fn is_collection(self) -> bool {
        matches!(
            self,
            Self::Mapping | Self::Sequence | Self::FlowMapping | Self::FlowSequence
        )
    }
}

/// The style of a flow scalar.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ScalarStyle {
    /// Unquoted.
    Plain,
    /// `'…'`.
    SingleQuoted,
    /// `"…"`.
    DoubleQuoted,
}

/// A block scalar and its header.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BlockScalarOwnership {
    /// The block scalar's index in [`YamlOwnership::nodes`].
    pub node: usize,
    /// The decoded `|`/`>` header.
    pub header: BlockHeader,
}

/// A block scalar header, decoded as YAML defines it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BlockHeader {
    /// `|` keeps line breaks; `>` folds them.
    pub folded: bool,
    /// What happens to the final line breaks.
    pub chomping: Chomping,
    /// The explicit indentation indicator (`|2`), if any.
    pub indentation: Option<u8>,
}

/// Block scalar chomping.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Chomping {
    /// Default: keep one final line break.
    Clip,
    /// `-`: drop the final line breaks.
    Strip,
    /// `+`: keep every final line break.
    Keep,
}

/// The layout `arm` proves. A hole becomes a placeholder only when its
/// shape proves it stays inside one scalar token; any other hole makes the
/// arm uncertain.
#[must_use]
pub fn arm_layout(body: &RenderedBody<'_>, arm: &RenderedArm) -> ArmLayout {
    match layout(body, arm) {
        Ok(owned) => ArmLayout::Known(owned),
        Err(uncertainty) => ArmLayout::Uncertain(uncertainty),
    }
}

/// The skeleton of `arm`: literals verbatim and a placeholder token `h<i>`
/// for the arm's `i`-th piece when it is a hole.
///
/// # Errors
///
/// [`LayoutUncertainty::Provenance`] when a piece does not resolve in the
/// body's source, and [`LayoutUncertainty::Overflow`] beyond
/// [`MAX_SKELETON_BYTES`].
pub fn arm_skeleton(
    body: &RenderedBody<'_>,
    arm: &RenderedArm,
) -> Result<Skeleton, LayoutUncertainty> {
    build_skeleton(body, arm, false)
}

fn layout(body: &RenderedBody<'_>, arm: &RenderedArm) -> Result<YamlOwnership, LayoutUncertainty> {
    let skeleton = build_skeleton(body, arm, false)?;
    let mut may_be_empty = false;
    for piece in &arm.pieces {
        match body.pieces.get(piece.0) {
            Some(RenderedPiece::Hole {
                shape: HoleShape::Unknown,
                ..
            }) => return Err(LayoutUncertainty::RawHole),
            Some(RenderedPiece::Hole {
                shape: HoleShape::ScalarText { nonempty: false },
                ..
            }) => may_be_empty = true,
            _ => {}
        }
    }
    let owned = ownership(skeleton)?;
    if may_be_empty {
        // An empty output is a permitted substitution too. It must keep every
        // node and its place; only a placeholder-only mapping value or block
        // item may vanish, leaving its entry with a null value.
        let empty = ownership(build_skeleton(body, arm, true)?)
            .map_err(|_| LayoutUncertainty::Substitution)?;
        if structure(&owned) != structure(&empty) {
            return Err(LayoutUncertainty::Substitution);
        }
    }
    Ok(owned)
}

/// Concatenate the arm's pieces: literals verbatim, holes as a placeholder
/// token (or nothing, for the empty substitution).
fn build_skeleton(
    body: &RenderedBody<'_>,
    arm: &RenderedArm,
    empty: bool,
) -> Result<Skeleton, LayoutUncertainty> {
    let mut text = String::new();
    let mut segments = Vec::new();
    for (index, piece) in arm.pieces.iter().enumerate() {
        let start = text.len();
        let placeholder = match body.pieces.get(piece.0) {
            Some(RenderedPiece::Text { span, .. }) => {
                let literal = body
                    .source
                    .get(span.start..span.end)
                    .ok_or(LayoutUncertainty::Provenance)?;
                if start + literal.len() > MAX_SKELETON_BYTES {
                    return Err(LayoutUncertainty::Overflow);
                }
                text.push_str(literal);
                false
            }
            Some(RenderedPiece::Hole { .. }) => {
                if !empty {
                    text.push('h');
                    text.push_str(&index.to_string());
                }
                true
            }
            None => return Err(LayoutUncertainty::Provenance),
        };
        segments.push(SkeletonSegment {
            range: Span::new(start, text.len()),
            piece: index,
            placeholder,
        });
    }
    if text.len() > MAX_SKELETON_BYTES {
        return Err(LayoutUncertainty::Overflow);
    }
    Ok(Skeleton { text, segments })
}

/// Parse the skeleton and map its structural nodes to pieces.
fn ownership(skeleton: Skeleton) -> Result<YamlOwnership, LayoutUncertainty> {
    let tree = parse_yaml(&skeleton.text).ok_or(LayoutUncertainty::Parse)?;
    let root = tree.root_node();
    if root.has_error() {
        return Err(LayoutUncertainty::Parse);
    }
    let mut nodes = Vec::new();
    let mut blocks = Vec::new();
    collect_nodes(root, None, false, &skeleton, &mut nodes, &mut blocks)?;
    if may_form_merge_key(&nodes, &skeleton) {
        return Err(LayoutUncertainty::MergeKey);
    }
    let decoded = if skeleton.segments.iter().any(|segment| segment.placeholder) {
        Err(Undecoded::Placeholders)
    } else {
        decode_documents(&nodes, &skeleton.text)
    };
    Ok(YamlOwnership {
        skeleton,
        nodes,
        blocks,
        decoded,
    })
}

fn collect_nodes(
    node: tree_sitter::Node<'_>,
    parent: Option<usize>,
    key: bool,
    skeleton: &Skeleton,
    nodes: &mut Vec<YamlNode>,
    blocks: &mut Vec<BlockScalarOwnership>,
) -> Result<(), LayoutUncertainty> {
    let kind = match node.kind() {
        "tag" | "alias" => return Err(LayoutUncertainty::TagOrAlias),
        "document" => Some(YamlNodeKind::Document),
        "block_mapping" => Some(YamlNodeKind::Mapping),
        "block_mapping_pair" => Some(YamlNodeKind::Pair),
        "block_sequence" => Some(YamlNodeKind::Sequence),
        "block_sequence_item" => Some(YamlNodeKind::Item),
        "flow_mapping" => Some(YamlNodeKind::FlowMapping),
        "flow_pair" => Some(YamlNodeKind::FlowPair),
        "flow_sequence" => Some(YamlNodeKind::FlowSequence),
        "plain_scalar" => Some(YamlNodeKind::Scalar(ScalarStyle::Plain)),
        "single_quote_scalar" => Some(YamlNodeKind::Scalar(ScalarStyle::SingleQuoted)),
        "double_quote_scalar" => Some(YamlNodeKind::Scalar(ScalarStyle::DoubleQuoted)),
        "block_scalar" => Some(YamlNodeKind::BlockScalar),
        "comment" => Some(YamlNodeKind::Comment),
        _ => None,
    };
    let mut own_parent = parent;
    // A key reaches only the first structural node below the entry's key.
    let mut child_key = key;
    if let Some(kind) = kind {
        let span = Span::new(node.start_byte(), node.end_byte());
        let index = nodes.len();
        nodes.push(YamlNode {
            parent,
            kind,
            key,
            span,
            pieces: covered_pieces(skeleton, span),
        });
        if kind == YamlNodeKind::BlockScalar {
            let text = skeleton.text.get(span.start..span.end).unwrap_or_default();
            blocks.push(BlockScalarOwnership {
                node: index,
                header: block_header(text).ok_or(LayoutUncertainty::Parse)?,
            });
        }
        // Scalars are leaves of the ownership structure.
        if matches!(kind, YamlNodeKind::Scalar(_) | YamlNodeKind::BlockScalar) {
            return Ok(());
        }
        own_parent = Some(index);
        child_key = false;
    }
    let entry_key = node.child_by_field_name("key");
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        // The key of a mapping entry, or a bare flow-mapping entry (`{a}`),
        // which is a key with a null value.
        let is_key = entry_key.is_some_and(|entry| entry.id() == child.id())
            || (node.kind() == "flow_mapping" && child.kind() == "flow_node");
        collect_nodes(
            child,
            own_parent,
            child_key || is_key,
            skeleton,
            nodes,
            blocks,
        )?;
    }
    Ok(())
}
/// The first and last arm-local pieces whose bytes intersect `span`.
fn covered_pieces(skeleton: &Skeleton, span: Span) -> Option<(usize, usize)> {
    let mut covered = skeleton
        .segments
        .iter()
        .filter(|segment| segment.range.start < span.end && span.start < segment.range.end);
    let first = covered.next()?.piece;
    let last = covered.next_back().map_or(first, |segment| segment.piece);
    Some((first, last))
}

/// Decode a block scalar header: `|` or `>`, then at most one chomping
/// indicator and one indentation digit in either order, as YAML 1.2 §8.1.1
/// defines it. The header ends at the first blank, comment or line break.
fn block_header(text: &str) -> Option<BlockHeader> {
    let mut chars = text.chars();
    let folded = match chars.next()? {
        '|' => false,
        '>' => true,
        _ => return None,
    };
    let mut chomping = None;
    let mut indentation = None;
    for c in chars {
        match c {
            '-' | '+' if chomping.is_none() => {
                chomping = Some(if c == '-' {
                    Chomping::Strip
                } else {
                    Chomping::Keep
                });
            }
            '1'..='9' if indentation.is_none() => indentation = c.to_digit(10)?.try_into().ok(),
            ' ' | '\t' | '\r' | '\n' | '#' => break,
            _ => return None,
        }
    }
    Some(BlockHeader {
        folded,
        chomping: chomping.unwrap_or(Chomping::Clip),
        indentation,
    })
}

/// Every document of a literal-only skeleton as Helm decodes it, or why
/// that is withheld: the literal decoder reads YAML 1.2 and agrees with
/// Helm only where no plain scalar diverges.
fn decode_documents(nodes: &[YamlNode], text: &str) -> Result<Vec<serde_json::Value>, Undecoded> {
    use serde::Deserialize as _;
    for (index, node) in nodes.iter().enumerate() {
        match node.kind {
            YamlNodeKind::Scalar(ScalarStyle::Plain) => {
                let spelling = text.get(node.span.start..node.span.end).unwrap_or_default();
                if let Some(divergence) = plain_scalar_divergence(spelling, node.key) {
                    return Err(Undecoded::Dialect(divergence));
                }
            }
            YamlNodeKind::Pair | YamlNodeKind::FlowPair
                if !nodes
                    .iter()
                    .any(|child| child.parent == Some(index) && child.key) =>
            {
                return Err(Undecoded::Dialect(DialectDivergence::NonStringKey));
            }
            kind if node.key && kind.is_collection() => return Err(Undecoded::CollectionKey),
            _ => {}
        }
    }
    serde_yaml::Deserializer::from_str(text)
        .map(serde_json::Value::deserialize)
        .collect::<Result<Vec<_>, _>>()
        .map_err(|_| Undecoded::Refused)
}

/// Whether a plain mapping key is, or a hole output can make it, the merge
/// key `<<` over a collection. Helm then merges the collection's entries
/// into the enclosing mapping; over a scalar or null it refuses the
/// document, so such a key cannot change a rendered layout.
fn may_form_merge_key(nodes: &[YamlNode], skeleton: &Skeleton) -> bool {
    nodes.iter().any(|key| {
        key.key
            && key.kind == YamlNodeKind::Scalar(ScalarStyle::Plain)
            && can_spell_merge_key(skeleton, key.span)
            && nodes
                .iter()
                .any(|value| value.parent == key.parent && !value.key && value.kind.is_collection())
    })
}

/// Whether the key at `span` is `<<`, or can become it when its holes
/// render: its literal bytes are at most two `<` and nothing else.
fn can_spell_merge_key(skeleton: &Skeleton, span: Span) -> bool {
    let mut literal = String::new();
    for segment in &skeleton.segments {
        let start = segment.range.start.max(span.start);
        let end = segment.range.end.min(span.end);
        if start < end && !segment.placeholder {
            literal.push_str(skeleton.text.get(start..end).unwrap_or_default());
        }
    }
    literal.len() <= 2
        && literal.chars().all(|c| c == '<')
        && (literal == "<<"
            || skeleton.segments.iter().any(|segment| {
                segment.placeholder
                    && segment.range.start < span.end
                    && span.start <= segment.range.start
            }))
}

/// The structure a substitution must preserve: every node's kind, key role
/// and parent, except a placeholder-only scalar that is a mapping value or
/// a block sequence item (an empty output leaves its entry with a null
/// value). A flow sequence element or a key made of placeholder bytes only
/// is kept, so its disappearance changes the structure.
fn structure(owned: &YamlOwnership) -> Vec<(YamlNodeKind, bool, Option<usize>)> {
    let skeleton = &owned.skeleton;
    let may_vanish = |node: &YamlNode| {
        let parent = node
            .parent
            .and_then(|parent| owned.nodes.get(parent))
            .map(|parent| parent.kind);
        matches!(node.kind, YamlNodeKind::Scalar(_))
            && !node.key
            && matches!(
                parent,
                Some(YamlNodeKind::Pair | YamlNodeKind::FlowPair | YamlNodeKind::Item)
            )
            && skeleton.segments.iter().all(|segment| {
                segment.placeholder
                    || segment.range.end <= node.span.start
                    || node.span.end <= segment.range.start
            })
    };
    // Kept nodes renumbered, so a vanished leaf shifts no parent reference.
    let mut kept_index = Vec::with_capacity(owned.nodes.len());
    let mut kept = Vec::new();
    for node in &owned.nodes {
        if may_vanish(node) {
            kept_index.push(None);
            continue;
        }
        kept_index.push(Some(kept.len()));
        let parent = node
            .parent
            .and_then(|parent| kept_index.get(parent).copied().flatten());
        kept.push((node.kind, node.key, parent));
    }
    kept
}

#[cfg(test)]
#[path = "tests/yaml.rs"]
mod tests;
