[package]
name = "test-util"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
color-eyre.workspace = true
flate2 = "1"
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true

tracing.workspace = true

vfs.workspace = true

googletest = "0"
lexpr = "0.2"
similar-asserts = "2"
tar = "0.4"
yaml-rust = "0.4"

[dev-dependencies]
indoc.workspace = true
tempfile.workspace = true
