[package]
name = "helm-schema-template-grammar"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
include = [
  "build.rs",
  "src/**",
  "tests/**",
  "grammars/tree-sitter-go-template/LICENSE",
  "grammars/tree-sitter-go-template/src/**",
]

[lints]
workspace = true

[features]
default = []

[build-dependencies]
cc = "1"

[dependencies]
tree-sitter-language = "0.1"

[dev-dependencies]
color-eyre.workspace = true
tree-sitter.workspace = true
test-util.workspace = true
similar-asserts = "2"
