apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickstart
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
