//! Exposes the language function for the vendored Go-template grammar.

/// Go-template grammar bindings.
pub mod go_template {
    #[expect(
        unsafe_code,
        reason = "the generated tree-sitter parser exposes its language through a C symbol"
    )]
    unsafe extern "C" {
        fn tree_sitter_gotmpl() -> *const ();
    }

    /// Returns the Go-template tree-sitter language function.
    #[must_use]
    pub fn language() -> tree_sitter_language::LanguageFn {
        // SAFETY: `tree_sitter_gotmpl` is generated by tree-sitter with the exact ABI expected by
        // `LanguageFn` and linked into this crate by the build script.
        #[expect(
            unsafe_code,
            reason = "constructing a LanguageFn requires the generated parser's C function"
        )]
        unsafe {
            tree_sitter_language::LanguageFn::from_raw(tree_sitter_gotmpl)
        }
    }
}

#[cfg(test)]
#[path = "tests/lib.rs"]
mod tests;
